# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shinyonazure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_92c508cd527044359b7c3e5b5e7107d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_44ae65c3d9e64df38bc5b18c6886be10 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92c508cd527044359b7c3e5b5e7107d0 }}/rocker/shiny:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shinyonazure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c9721201cbff47a79305a92d72434e1e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92c508cd527044359b7c3e5b5e7107d0 }}/rocker/shiny:${{ github.sha }}'